version: '3.4'

services:
  containerwebtest:
    image: containerwebtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
